### ISSUE TITLE
create-dataset.sh not working

### ISSUE THREAD

**Issue by ulrichSchreiner** [Jorl17/open-elevation#10]
hi,

when starting `create-dataset.sh` in your docker image (`openelevation/open-elevation`)  the RAR archives are downloaded but they cannot be unrar'ed. the `unrar` in your image seems to be corrupt, it complains with **failed**.
~~~
root@df71da380484:/code/data# unrar e SRTM_SE_250m_TIF.rar

unrar 0.0.1  Copyright (C) 2004  Ben Asselstine, Jeroen Dekkers


Extracting from /code/data/SRTM_SE_250m_TIF.rar

Extracting  SRTM_SE_250m.tif                                          Failed    
Extracting  readme.txt                                                Failed    
2 Failed
~~~
this happens for all RAR files, but the RAR files ar ok, the `unrar` is corrupt.

The real bad thing is, that the `create-dataset` script calls `create-tiles.sh` which also fails (there are not TIF files) and afterwards the RAR files are deleted!

As the download of the RAR's is time-expensive (i have to wait about 45min), i had to download them again and manually unrar them (with a ubuntu 16.04 image where the unrar works for me).

perhaps you should use the `set -eu` in your `create-dataset.sh` and in your downloader too.

**Comment by Jorl17** [comment]
Hi!

Thanks for your suggestions. It appears unrar-free does not support the rarfiles provided by the datasource. I have replaced it with unar. I could have sworn I had used this exact same docker image while setting up https://open-elevation.com but I might be confused.

Rgarding `set -eu`, I have added them in those places, thanks for the suggestion!

I haven't had the time to test the changes yet (very slow internet where I am), but I have pushed a new docker image with these fixes and will test when I have time. These fixes are in commit https://github.com/Jorl17/open-elevation/commit/e1e633d51ebf73bf84294bdc5e2da23491edb14f

Thanks again!
