### ISSUE TITLE
Invalid Json

### ISSUE THREAD

**Issue by habib-farhan** [Jorl17/open-elevation#13]
Hi,

I am trying to get elevation for a bunch of points, but i keep getting invalid json error or sometime "Locations is required in the body".
Could anyone help me witht that?
here is my code.
`     function routeToLineString(route){
          var lineCoordinates = [],
                         cordinate = {},
		                      i,
			     latLng;

         for (i = 0; i < route.coordinates.length; i++) {
            latLng = L.latLng(route.coordinates[i]);
            cordinate["latitude"] = latLng.lat;
            cordinate["longitude"]  = latLng.lng;
            lineCoordinates.push(cordinate);
        }
    var locationJson = {
      "Locations": lineCoordinates
     };

       getElevation(JSON.stringify(locationJson));		
   }
    function getElevation(locationData){
       $.ajax({
        headers: {
        "Accept" : "application/json",
        "Content-Type" : "application/json"
      },
      type: 'POST',
      url: 'https://api.open-elevation.com/api/v1/lookup',
      data: locationData,
      success: function(data){
        console.log(data);
      }
    });
   }

`

**Comment by Jorl17** [comment]
Hi!

Could you provide a working minimal example (with coordinates) so that I can test? Something I can paste into an AJAX/CSRF-ready terminal and watch it crash and burn? Your example assumes  that `route.coordinates` exists.

I have also noticed that your `Locations` parameter is spelled with a capital `L`. Have you tried with a lower-case `l`?

Cheers

**Comment by habib-farhan** [comment]
Thanks a lot for the blazing fast reply with the solution.
lower case `l` worked.
The error always showed "Location" is missing.
so i used with capital L.
Thanks anyway.  (Y)

**Comment by Jorl17** [comment]
Glad it got solved :)
