### ISSUE TITLE
Data for northern part of the globe missing?

### ISSUE THREAD

**Issue by heyman** [Jorl17/open-elevation#16]
It seems like the public API, as well as the data that the included scripts can download (http://gisweb.ciat.cgiar.org/TRMM/SRTM_Resampled_250m/) doesn't cover the northern part of the world (for example, two thirds of Sweden are missing).

Do you know of any data source that covers the whole world, and how it can be set up to work with the open-elevation server?

Thanks!

**Comment by Jorl17** [comment]
Hi, I will be coming back with a reply soon. I've been very busy with my work :)

**Comment by mitkin** [comment]
Hi, would you consider using ASTER DEM or similar instead of SRTM which only covers latitudes in the range of  +60/-60 deg?

**Comment by jeev20** [comment]
Facing same issue for Norwegian locations.

**Comment by nnhubbard** [comment]
@Jorl17 Any updates on this?

**Comment by Jorl17** [comment]
Hi. We are currently using the 250m SRTM dataset.

On our public offering, we have no plans of using another dataset. We are nonetheless considering adding support for other datasets in a possible paid offering. Unfortunately, since donations are so rare, we need to find a way to make some money :)
