### ISSUE TITLE
Large POST request "Invalid JSON" error

### ISSUE THREAD

**Issue by GeoffreyCoulaud** [Jorl17/open-elevation#19]
Hello ! I'll start by saying that what you're doing is awesome and it helps a lot, really !

So, i try to make a big POST request of coordinates (around 6 000) and i'm sure i format the JSON sent in the way required in the docs, but i keep getting the data {"error": "Invalid JSON."} anyway.

Just to be clear, it is only exceptionnal requests, at most once a week, but am i overloading the server ?
Or am i forgetting something obvious ?

**Comment by DigNZ** [comment]
I just found this same issue, but setting the content type header fixed it: Content-Type: application/json

I'm only looking at 200 - 500 locations though.

**Comment by GeoffreyCoulaud** [comment]
Yes it worked ! I stupidly copied "content-type" as the header (without uppercase C and T) and it was the problem !

Oh, and to help anyone trying the same thing : Don't. You'll get a 504 Gateway Timeout with this much coordinates !
