### ISSUE TITLE
500 server error on previously working data

### ISSUE THREAD

**Issue by NickoftheSouth** [Jorl17/open-elevation#22]
Hello we've been using the open elevation api in an app we are working on for a few months.
For some reason when I was testing today I noticed the call to get the elevation to;

`https://api.open-elevation.com/api/v1/lookup`

was returning a 500 server error like so;
`<html>
    <head>
        <title>500 Internal Server Error</title>
    </head>
    <body bgcolor="white">
        <center>
            <h1>500 Internal Server Error</h1>
        </center>
        <hr>
        <center>nginx/1.13.5</center>
    </body>
</html>

`

I'm adament this was working as recently as Friday with exactly the same data.

Here's the json body of the request the app is sending if that helps;

`{"locations":[{"latitude":-41.21343,"longitude":174.81054},{"latitude":-41.21007,"longitude":174.81228000000002},{"latitude":-41.20718,"longitude":174.81186000000002},{"latitude":-41.20389,"longitude":174.81492},{"latitude":-41.203950000000006,"longitude":174.81595000000002},{"latitude":-41.204660000000004,"longitude":174.81854},{"latitude":-41.203540000000004,"longitude":174.82162000000002},{"latitude":-41.197720000000004,"longitude":174.82458000000003},{"latitude":-41.193940000000005,"longitude":174.82951000000003},{"latitude":-41.186440000000005,"longitude":174.83214},{"latitude":-41.181360000000005,"longitude":174.82883},{"latitude":-41.17313,"longitude":174.83082000000002},{"latitude":-41.15881,"longitude":174.83709000000002},{"latitude":-41.147420000000004,"longitude":174.84374000000003},{"latitude":-41.13947,"longitude":174.84471000000002},{"latitude":-41.1287,"longitude":174.84489000000002},{"latitude":-41.11077,"longitude":174.86144000000002},{"latitude":-41.1058,"longitude":174.86772000000002},{"latitude":-41.103790000000004,"longitude":174.86969000000002},{"latitude":-41.093320000000006,"longitude":174.86890000000002},{"latitude":-41.08944,"longitude":174.86686},{"latitude":-41.082750000000004,"longitude":174.86904},{"latitude":-41.075300000000006,"longitude":174.87462000000002},{"latitude":-41.0643,"longitude":174.87733},{"latitude":-41.052710000000005,"longitude":174.87740000000002},{"latitude":-41.04749,"longitude":174.87902000000003},{"latitude":-41.03728,"longitude":174.8855},{"latitude":-41.033190000000005,"longitude":174.88909},{"latitude":-41.033030000000004,"longitude":174.89287000000002},{"latitude":-41.030620000000006,"longitude":174.89695},{"latitude":-41.02604,"longitude":174.90182000000001},{"latitude":-41.01711,"longitude":174.9153},{"latitude":-41.01012,"longitude":174.92296000000002},{"latitude":-41.005700000000004,"longitude":174.92724},{"latitude":-41.002860000000005,"longitude":174.93427000000003},{"latitude":-40.991200000000006,"longitude":174.94946000000002},{"latitude":-40.986470000000004,"longitude":174.95725000000002},{"latitude":-40.98257,"longitude":174.96167000000003},{"latitude":-40.98091,"longitude":174.97454000000002},{"latitude":-40.97569,"longitude":174.97865000000002},{"latitude":-40.970780000000005,"longitude":174.98304000000002},{"latitude":-40.953030000000005,"longitude":174.98862000000003},{"latitude":-40.93558,"longitude":174.99454},{"latitude":-40.92935000000001,"longitude":174.99244000000002},{"latitude":-40.91714,"longitude":174.99193000000002},{"latitude":-40.908170000000005,"longitude":175.00007000000002},{"latitude":-40.89077,"longitude":175.02238000000003},{"latitude":-40.8789,"longitude":175.02685000000002},{"latitude":-40.86809,"longitude":175.03535000000002},{"latitude":-40.863640000000004,"longitude":175.04523},{"latitude":-40.858430000000006,"longitude":175.05429},{"latitude":-40.850460000000005,"longitude":175.06437000000003},{"latitude":-40.845290000000006,"longitude":175.08142},{"latitude":-40.828320000000005,"longitude":175.09613000000002},{"latitude":-40.81898,"longitude":175.10781},{"latitude":-40.8029,"longitude":175.12075000000002},{"latitude":-40.78183000000001,"longitude":175.13744000000003},{"latitude":-40.77018,"longitude":175.14520000000002},{"latitude":-40.76565,"longitude":175.14970000000002},{"latitude":-40.76034000000001,"longitude":175.15745},{"latitude":-40.75836,"longitude":175.16145},{"latitude":-40.75182,"longitude":175.16682},{"latitude":-40.74403,"longitude":175.16966000000002},{"latitude":-40.74016,"longitude":175.18039000000002},{"latitude":-40.734700000000004,"longitude":175.19122000000002},{"latitude":-40.73339,"longitude":175.20019000000002},{"latitude":-40.725350000000006,"longitude":175.2115},{"latitude":-40.71916,"longitude":175.21377},{"latitude":-40.699850000000005,"longitude":175.22362},{"latitude":-40.69556,"longitude":175.22942},{"latitude":-40.68404,"longitude":175.23984000000002},{"latitude":-40.67011,"longitude":175.24139000000002},{"latitude":-40.66516,"longitude":175.24837000000002},{"latitude":-40.656180000000006,"longitude":175.25197000000003},{"latitude":-40.62917,"longitude":175.27959},{"latitude":-40.617360000000005,"longitude":175.29132},{"latitude":-40.610510000000005,"longitude":175.299},{"latitude":-40.592960000000005,"longitude":175.29923000000002},{"latitude":-40.5765,"longitude":175.27267},{"latitude":-40.57314,"longitude":175.26878000000002},{"latitude":-40.566790000000005,"longitude":175.2655},{"latitude":-40.556110000000004,"longitude":175.26852000000002},{"latitude":-40.538940000000004,"longitude":175.27621000000002},{"latitude":-40.519780000000004,"longitude":175.27575000000002},{"latitude":-40.500960000000006,"longitude":175.28371},{"latitude":-40.494620000000005,"longitude":175.27953000000002},{"latitude":-40.485040000000005,"longitude":175.28287},{"latitude":-40.473530000000004,"longitude":175.28554000000003},{"latitude":-40.46533,"longitude":175.28871},{"latitude":-40.42915,"longitude":175.30214},{"latitude":-40.38069,"longitude":175.3187},{"latitude":-40.332040000000006,"longitude":175.34432},{"latitude":-40.29061,"longitude":175.36439000000001},{"latitude":-40.26565,"longitude":175.37957},{"latitude":-40.22005,"longitude":175.42399},{"latitude":-40.208090000000006,"longitude":175.40703000000002},{"latitude":-40.200500000000005,"longitude":175.39337},{"latitude":-40.19115,"longitude":175.38865},{"latitude":-40.17363,"longitude":175.38661000000002},{"latitude":-40.15437,"longitude":175.40401000000003},{"latitude":-40.139410000000005,"longitude":175.41770000000002},{"latitude":-40.13266,"longitude":175.41856},{"latitude":-40.122890000000005,"longitude":175.41941000000003},{"latitude":-40.08597,"longitude":175.41260000000003},{"latitude":-40.06917,"longitude":175.41892},{"latitude":-40.0484,"longitude":175.43631000000002},{"latitude":-40.035540000000005,"longitude":175.44437000000002},{"latitude":-40.0306,"longitude":175.45191000000003},{"latitude":-40.02772,"longitude":175.46614000000002},{"latitude":-40.020860000000006,"longitude":175.48044000000002},{"latitude":-40.000910000000005,"longitude":175.50847000000002},{"latitude":-39.99419,"longitude":175.51517},{"latitude":-39.979380000000006,"longitude":175.52117},{"latitude":-39.97104,"longitude":175.52072},{"latitude":-39.96603,"longitude":175.52389000000002},{"latitude":-39.963010000000004,"longitude":175.53383000000002},{"latitude":-39.95754,"longitude":175.54795000000001},{"latitude":-39.95264,"longitude":175.56594},{"latitude":-39.94337,"longitude":175.56927000000002},{"latitude":-39.93567,"longitude":175.56993000000003},{"latitude":-39.932320000000004,"longitude":175.57488},{"latitude":-39.92822,"longitude":175.57827},{"latitude":-39.9253,"longitude":175.58717000000001},{"latitude":-39.922200000000004,"longitude":175.59355000000002},{"latitude":-39.924690000000005,"longitude":175.60669000000001},{"latitude":-39.926410000000004,"longitude":175.61332000000002},{"latitude":-39.924200000000006,"longitude":175.621},{"latitude":-39.924260000000004,"longitude":175.62983000000003},{"latitude":-39.91283000000001,"longitude":175.63596},{"latitude":-39.89016,"longitude":175.66347000000002},{"latitude":-39.88158000000001,"longitude":175.67422000000002},{"latitude":-39.876920000000005,"longitude":175.67459000000002},{"latitude":-39.87209,"longitude":175.68069000000003},{"latitude":-39.870630000000006,"longitude":175.68952000000002},{"latitude":-39.865570000000005,"longitude":175.69978},{"latitude":-39.85463,"longitude":175.72644000000003},{"latitude":-39.841860000000004,"longitude":175.74172000000002},{"latitude":-39.836400000000005,"longitude":175.77074000000002},{"latitude":-39.83184000000001,"longitude":175.78056},{"latitude":-39.827940000000005,"longitude":175.78127},{"latitude":-39.82372,"longitude":175.77643},{"latitude":-39.81275,"longitude":175.78474000000003},{"latitude":-39.806810000000006,"longitude":175.79562},{"latitude":-39.803470000000004,"longitude":175.79852000000002},{"latitude":-39.79921,"longitude":175.79680000000002},{"latitude":-39.796820000000004,"longitude":175.78962},{"latitude":-39.792500000000004,"longitude":175.78495},{"latitude":-39.779070000000004,"longitude":175.787},{"latitude":-39.77423,"longitude":175.79129},{"latitude":-39.760560000000005,"longitude":175.80521000000002},{"latitude":-39.758370000000006,"longitude":175.81326},{"latitude":-39.76041,"longitude":175.82257},{"latitude":-39.75755,"longitude":175.82834000000003},{"latitude":-39.751090000000005,"longitude":175.8343},{"latitude":-39.744490000000006,"longitude":175.83479000000003},{"latitude":-39.7409,"longitude":175.83839},{"latitude":-39.73617,"longitude":175.84145},{"latitude":-39.731550000000006,"longitude":175.84389000000002},{"latitude":-39.71177,"longitude":175.83747000000002},{"latitude":-39.69722,"longitude":175.82419000000002},{"latitude":-39.68672,"longitude":175.80730000000003},{"latitude":-39.68506,"longitude":175.80519},{"latitude":-39.684610000000006,"longitude":175.80135},{"latitude":-39.676930000000006,"longitude":175.79819},{"latitude":-39.67443,"longitude":175.79409},{"latitude":-39.66613,"longitude":175.78476},{"latitude":-39.65955,"longitude":175.78092},{"latitude":-39.65341,"longitude":175.77227000000002},{"latitude":-39.646710000000006,"longitude":175.76797000000002},{"latitude":-39.6357,"longitude":175.76815000000002},{"latitude":-39.6287,"longitude":175.76042},{"latitude":-39.62342,"longitude":175.76103},{"latitude":-39.61751,"longitude":175.76161000000002},{"latitude":-39.61218,"longitude":175.76004},{"latitude":-39.60408,"longitude":175.76076},{"latitude":-39.59756,"longitude":175.76467000000002},{"latitude":-39.59369,"longitude":175.76339000000002},{"latitude":-39.59208,"longitude":175.75422},{"latitude":-39.59194,"longitude":175.74511},{"latitude":-39.58035,"longitude":175.72420000000002},{"latitude":-39.57898,"longitude":175.71672},{"latitude":-39.572120000000005,"longitude":175.70961000000003},{"latitude":-39.568110000000004,"longitude":175.70006},{"latitude":-39.564080000000004,"longitude":175.69762},{"latitude":-39.56006,"longitude":175.69968},{"latitude":-39.55427,"longitude":175.69542},{"latitude":-39.550520000000006,"longitude":175.68627},{"latitude":-39.54142,"longitude":175.68247000000002},{"latitude":-39.53423,"longitude":175.68060000000003},{"latitude":-39.52474,"longitude":175.6842},{"latitude":-39.51371,"longitude":175.68422},{"latitude":-39.50567,"longitude":175.67467000000002},{"latitude":-39.499230000000004,"longitude":175.67403000000002},{"latitude":-39.48771,"longitude":175.67030000000003},{"latitude":-39.477700000000006,"longitude":175.66837},{"latitude":-39.46501000000001,"longitude":175.67299000000003},{"latitude":-39.4472,"longitude":175.6798},{"latitude":-39.439350000000005,"longitude":175.68168000000003},{"latitude":-39.42036,"longitude":175.68716},{"latitude":-39.39914,"longitude":175.6981},{"latitude":-39.382670000000005,"longitude":175.7093},{"latitude":-39.31987,"longitude":175.72906},{"latitude":-39.303490000000004,"longitude":175.74118},{"latitude":-39.286910000000006,"longitude":175.74112000000002},{"latitude":-39.28177,"longitude":175.74308000000002},{"latitude":-39.27819,"longitude":175.74426000000003},{"latitude":-39.269450000000006,"longitude":175.7373},{"latitude":-39.26465,"longitude":175.73298000000003},{"latitude":-39.24989,"longitude":175.73608000000002},{"latitude":-39.241620000000005,"longitude":175.72682},{"latitude":-39.237660000000005,"longitude":175.72734000000003},{"latitude":-39.2314,"longitude":175.73494000000002},{"latitude":-39.21905,"longitude":175.73477000000003},{"latitude":-39.2152,"longitude":175.73905000000002},{"latitude":-39.209250000000004,"longitude":175.74868},{"latitude":-39.20485,"longitude":175.75583},{"latitude":-39.199670000000005,"longitude":175.7564},{"latitude":-39.193580000000004,"longitude":175.75592},{"latitude":-39.18751,"longitude":175.757},{"latitude":-39.185370000000006,"longitude":175.76079000000001},{"latitude":-39.18388,"longitude":175.76586},{"latitude":-39.182500000000005,"longitude":175.76308},{"latitude":-39.18281,"longitude":175.75859000000003},{"latitude":-39.180330000000005,"longitude":175.76113},{"latitude":-39.17996,"longitude":175.76339000000002},{"latitude":-39.17969,"longitude":175.7656},{"latitude":-39.17922,"longitude":175.76836},{"latitude":-39.17578,"longitude":175.76905000000002},{"latitude":-39.174040000000005,"longitude":175.76752000000002},{"latitude":-39.17344000000001,"longitude":175.76542},{"latitude":-39.170190000000005,"longitude":175.76615},{"latitude":-39.158730000000006,"longitude":175.76911},{"latitude":-39.156980000000004,"longitude":175.76814000000002},{"latitude":-39.15619,"longitude":175.76531000000003},{"latitude":-39.154590000000006,"longitude":175.76959000000002},{"latitude":-39.15415,"longitude":175.7672},{"latitude":-39.15316,"longitude":175.76807000000002},{"latitude":-39.14217,"longitude":175.77264000000002},{"latitude":-39.120250000000006,"longitude":175.79957000000002},{"latitude":-39.108140000000006,"longitude":175.80737000000002},{"latitude":-39.09091,"longitude":175.80890000000002},{"latitude":-39.076220000000006,"longitude":175.80898000000002},{"latitude":-39.065470000000005,"longitude":175.81833},{"latitude":-39.05324,"longitude":175.8206},{"latitude":-39.043150000000004,"longitude":175.8145},{"latitude":-39.03842,"longitude":175.81604000000002},{"latitude":-39.02178,"longitude":175.80919},{"latitude":-39.001470000000005,"longitude":175.80398000000002},{"latitude":-38.99537,"longitude":175.80557000000002},{"latitude":-38.9887,"longitude":175.81511},{"latitude":-38.98322,"longitude":175.82018000000002},{"latitude":-38.97858,"longitude":175.82776},{"latitude":-38.955540000000006,"longitude":175.84036},{"latitude":-38.95367,"longitude":175.84374000000003},{"latitude":-38.950010000000006,"longitude":175.84896},{"latitude":-38.94502000000001,"longitude":175.85145000000003},{"latitude":-38.94241,"longitude":175.85641},{"latitude":-38.93829,"longitude":175.86044},{"latitude":-38.935950000000005,"longitude":175.86867},{"latitude":-38.92974,"longitude":175.87834},{"latitude":-38.92568,"longitude":175.88645000000002},{"latitude":-38.917460000000005,"longitude":175.89294},{"latitude":-38.91187,"longitude":175.89946},{"latitude":-38.91017,"longitude":175.905},{"latitude":-38.90708,"longitude":175.92228},{"latitude":-38.9057,"longitude":175.93171},{"latitude":-38.904970000000006,"longitude":175.93937000000003},{"latitude":-38.895590000000006,"longitude":175.94733000000002},{"latitude":-38.887130000000006,"longitude":175.95371},{"latitude":-38.88741,"longitude":175.95979000000003},{"latitude":-38.882870000000004,"longitude":175.96662},{"latitude":-38.883340000000004,"longitude":175.96837000000002},{"latitude":-38.881220000000006,"longitude":175.971},{"latitude":-38.88035,"longitude":175.97499000000002},{"latitude":-38.878400000000006,"longitude":175.98231},{"latitude":-38.87874,"longitude":175.98514},{"latitude":-38.87726,"longitude":175.98901},{"latitude":-38.875460000000004,"longitude":175.99154000000001},{"latitude":-38.875800000000005,"longitude":175.9983},{"latitude":-38.873000000000005,"longitude":176.00363000000002},{"latitude":-38.866460000000004,"longitude":176.00791},{"latitude":-38.85661,"longitude":176.01285000000001},{"latitude":-38.85316,"longitude":176.02337000000003},{"latitude":-38.85286,"longitude":176.03038},{"latitude":-38.85398,"longitude":176.03856000000002},{"latitude":-38.855830000000005,"longitude":176.04803},{"latitude":-38.854000000000006,"longitude":176.05234000000002},{"latitude":-38.84384,"longitude":176.05924000000002},{"latitude":-38.83587,"longitude":176.06500000000003},{"latitude":-38.825320000000005,"longitude":176.06906},{"latitude":-38.81716,"longitude":176.07757},{"latitude":-38.80702,"longitude":176.07938000000001},{"latitude":-38.79956000000001,"longitude":176.07652000000002},{"latitude":-38.78728,"longitude":176.07641},{"latitude":-38.769450000000006,"longitude":176.07609000000002},{"latitude":-38.741440000000004,"longitude":176.07274},{"latitude":-38.738910000000004,"longitude":176.07253},{"latitude":-38.735780000000005,"longitude":176.07557000000003},{"latitude":-38.715230000000005,"longitude":176.10641},{"latitude":-38.70667,"longitude":176.11179},{"latitude":-38.70429,"longitude":176.11175},{"latitude":-38.698890000000006,"longitude":176.11215},{"latitude":-38.68339,"longitude":176.11454},{"latitude":-38.677060000000004,"longitude":176.11681000000002},{"latitude":-38.67226,"longitude":176.11419},{"latitude":-38.669380000000004,"longitude":176.10591000000002},{"latitude":-38.665380000000006,"longitude":176.10138},{"latitude":-38.641850000000005,"longitude":176.09930000000003},{"latitude":-38.637150000000005,"longitude":176.09723000000002},{"latitude":-38.62379,"longitude":176.09961},{"latitude":-38.621340000000004,"longitude":176.09882000000002},{"latitude":-38.60918,"longitude":176.09161},{"latitude":-38.60571,"longitude":176.08171000000002},{"latitude":-38.60305,"longitude":176.07005},{"latitude":-38.59492,"longitude":176.06132000000002},{"latitude":-38.58952,"longitude":176.05841},{"latitude":-38.58558,"longitude":176.06337000000002},{"latitude":-38.57858,"longitude":176.06041000000002},{"latitude":-38.572340000000004,"longitude":176.05130000000003},{"latitude":-38.556090000000005,"longitude":176.04449000000002},{"latitude":-38.54514,"longitude":176.04291},{"latitude":-38.533730000000006,"longitude":176.05183000000002},{"latitude":-38.52676,"longitude":176.04902},{"latitude":-38.517210000000006,"longitude":176.04632},{"latitude":-38.495580000000004,"longitude":176.05272000000002},{"latitude":-38.48425,"longitude":176.0543},{"latitude":-38.472500000000004,"longitude":176.05900000000003},{"latitude":-38.462790000000005,"longitude":176.05869},{"latitude":-38.45423,"longitude":176.05827000000002},{"latitude":-38.43905,"longitude":176.05895},{"latitude":-38.425520000000006,"longitude":176.05707},{"latitude":-38.409580000000005,"longitude":176.05221},{"latitude":-38.40122,"longitude":176.04991},{"latitude":-38.396460000000005,"longitude":176.03852},{"latitude":-38.39481,"longitude":176.0201},{"latitude":-38.39166,"longitude":176.01229},{"latitude":-38.38251,"longitude":176.00422},{"latitude":-38.374700000000004,"longitude":176.00056},{"latitude":-38.36535000000001,"longitude":176.00263},{"latitude":-38.360730000000004,"longitude":176.00201},{"latitude":-38.35432,"longitude":176.00509000000002},{"latitude":-38.345470000000006,"longitude":176.00723000000002},{"latitude":-38.33408,"longitude":176.00378},{"latitude":-38.326600000000006,"longitude":175.99209000000002},{"latitude":-38.316230000000004,"longitude":175.97961},{"latitude":-38.309340000000006,"longitude":175.97043000000002},{"latitude":-38.30151,"longitude":175.96485},{"latitude":-38.299490000000006,"longitude":175.95945},{"latitude":-38.298370000000006,"longitude":175.94172},{"latitude":-38.293330000000005,"longitude":175.93559000000002},{"latitude":-38.28869,"longitude":175.93223},{"latitude":-38.2873,"longitude":175.92139},{"latitude":-38.28562,"longitude":175.91461},{"latitude":-38.28042000000001,"longitude":175.90416000000002},{"latitude":-38.26914,"longitude":175.89961000000002},{"latitude":-38.2639,"longitude":175.89865},{"latitude":-38.259040000000006,"longitude":175.89415000000002},{"latitude":-38.25113,"longitude":175.88845},{"latitude":-38.23711,"longitude":175.88143000000002},{"latitude":-38.22111,"longitude":175.87482000000003},{"latitude":-38.21464,"longitude":175.87108},{"latitude":-38.210420000000006,"longitude":175.86912},{"latitude":-38.197860000000006,"longitude":175.86827000000002},{"latitude":-38.186040000000006,"longitude":175.86188},{"latitude":-38.17987,"longitude":175.86174000000003},{"latitude":-38.17633,"longitude":175.86040000000003},{"latitude":-38.17259,"longitude":175.85936},{"latitude":-38.16821,"longitude":175.85590000000002},{"latitude":-38.15936000000001,"longitude":175.85644000000002},{"latitude":-38.156670000000005,"longitude":175.85319},{"latitude":-38.145500000000006,"longitude":175.84781},{"latitude":-38.13882,"longitude":175.82825000000003},{"latitude":-38.1327,"longitude":175.82496},{"latitude":-38.124100000000006,"longitude":175.8266},{"latitude":-38.118190000000006,"longitude":175.82437000000002},{"latitude":-38.09984,"longitude":175.81683},{"latitude":-38.0861,"longitude":175.8102},{"latitude":-38.08372,"longitude":175.80747000000002},{"latitude":-38.07875000000001,"longitude":175.79525},{"latitude":-38.07271,"longitude":175.79153000000002},{"latitude":-38.06725,"longitude":175.78948000000003},{"latitude":-38.063680000000005,"longitude":175.79238},{"latitude":-38.05787,"longitude":175.78885000000002},{"latitude":-38.054460000000006,"longitude":175.78343},{"latitude":-38.050520000000006,"longitude":175.78017000000003},{"latitude":-38.04554,"longitude":175.78150000000002},{"latitude":-38.0412,"longitude":175.78528},{"latitude":-38.04032,"longitude":175.78737},{"latitude":-38.035630000000005,"longitude":175.78920000000002},{"latitude":-38.0276,"longitude":175.78917},{"latitude":-38.01019,"longitude":175.77302},{"latitude":-38.00169,"longitude":175.76732},{"latitude":-37.995720000000006,"longitude":175.76746000000003},{"latitude":-37.98989,"longitude":175.76672000000002},{"latitude":-37.986560000000004,"longitude":175.76814000000002},{"latitude":-37.985310000000005,"longitude":175.76680000000002},{"latitude":-37.980990000000006,"longitude":175.76272},{"latitude":-37.98049,"longitude":175.76002000000003},{"latitude":-37.97598,"longitude":175.75486},{"latitude":-37.97504,"longitude":175.74963000000002},{"latitude":-37.974230000000006,"longitude":175.74585000000002},{"latitude":-37.97486,"longitude":175.74295},{"latitude":-37.982780000000005,"longitude":175.73457000000002},{"latitude":-37.98617,"longitude":175.72606000000002},{"latitude":-37.98559,"longitude":175.71560000000002},{"latitude":-37.983720000000005,"longitude":175.70614},{"latitude":-37.98002,"longitude":175.70233000000002},{"latitude":-37.97419,"longitude":175.69473000000002},{"latitude":-37.959210000000006,"longitude":175.68615000000003},{"latitude":-37.95445,"longitude":175.6817},{"latitude":-37.952670000000005,"longitude":175.67663000000002},{"latitude":-37.94467,"longitude":175.67078},{"latitude":-37.94308,"longitude":175.66471},{"latitude":-37.94478,"longitude":175.65785000000002},{"latitude":-37.94727,"longitude":175.6535},{"latitude":-37.94684,"longitude":175.64430000000002},{"latitude":-37.951710000000006,"longitude":175.63108000000003},{"latitude":-37.95136,"longitude":175.62147000000002},{"latitude":-37.94782,"longitude":175.61271000000002},{"latitude":-37.94753,"longitude":175.60372},{"latitude":-37.94615,"longitude":175.59051000000002},{"latitude":-37.94328,"longitude":175.58399000000003},{"latitude":-37.938700000000004,"longitude":175.57680000000002},{"latitude":-37.925230000000006,"longitude":175.56642000000002},{"latitude":-37.91481,"longitude":175.5491},{"latitude":-37.907000000000004,"longitude":175.52751},{"latitude":-37.89316,"longitude":175.50179000000003},{"latitude":-37.88376,"longitude":175.49178},{"latitude":-37.869600000000005,"longitude":175.47278},{"latitude":-37.869330000000005,"longitude":175.45861000000002},{"latitude":-37.86139,"longitude":175.45514000000003},{"latitude":-37.85768,"longitude":175.45355},{"latitude":-37.823640000000005,"longitude":175.43446},{"latitude":-37.817660000000004,"longitude":175.42653},{"latitude":-37.80709,"longitude":175.41293000000002},{"latitude":-37.80033,"longitude":175.40023000000002},{"latitude":-37.792660000000005,"longitude":175.3933},{"latitude":-37.78401,"longitude":175.39057000000003},{"latitude":-37.78016,"longitude":175.38678000000002},{"latitude":-37.7751,"longitude":175.37446000000003},{"latitude":-37.763630000000006,"longitude":175.38660000000002},{"latitude":-37.68667000000001,"longitude":175.33831},{"latitude":-37.680220000000006,"longitude":175.31787000000003},{"latitude":-37.67002,"longitude":175.3042},{"latitude":-37.665380000000006,"longitude":175.29921000000002},{"latitude":-37.659130000000005,"longitude":175.29525},{"latitude":-37.652210000000004,"longitude":175.28865000000002},{"latitude":-37.64934,"longitude":175.28056},{"latitude":-37.64842,"longitude":175.27395},{"latitude":-37.64569,"longitude":175.26006},{"latitude":-37.642570000000006,"longitude":175.25748000000002},{"latitude":-37.633390000000006,"longitude":175.25148000000002},{"latitude":-37.630970000000005,"longitude":175.24785000000003},{"latitude":-37.62747,"longitude":175.23652},{"latitude":-37.620850000000004,"longitude":175.21197},{"latitude":-37.621660000000006,"longitude":175.20712},{"latitude":-37.621880000000004,"longitude":175.20506},{"latitude":-37.62106,"longitude":175.20305000000002},{"latitude":-37.613020000000006,"longitude":175.19447000000002},{"latitude":-37.611180000000004,"longitude":175.19155},{"latitude":-37.611940000000004,"longitude":175.18853000000001},{"latitude":-37.61209,"longitude":175.18616},{"latitude":-37.60869,"longitude":175.18476},{"latitude":-37.603350000000006,"longitude":175.17361000000002},{"latitude":-37.600120000000004,"longitude":175.16580000000002},{"latitude":-37.59322,"longitude":175.15986},{"latitude":-37.581860000000006,"longitude":175.15907},{"latitude":-37.574180000000005,"longitude":175.15942},{"latitude":-37.565810000000006,"longitude":175.15902000000003},{"latitude":-37.560550000000006,"longitude":175.15946000000002},{"latitude":-37.551610000000004,"longitude":175.15868},{"latitude":-37.533750000000005,"longitude":175.15922},{"latitude":-37.52367,"longitude":175.16059},{"latitude":-37.516540000000006,"longitude":175.16504},{"latitude":-37.507580000000004,"longitude":175.16681000000003},{"latitude":-37.49306,"longitude":175.16180000000003},{"latitude":-37.483670000000004,"longitude":175.1603},{"latitude":-37.45234,"longitude":175.15314},{"latitude":-37.438140000000004,"longitude":175.14581},{"latitude":-37.433370000000004,"longitude":175.13984000000002},{"latitude":-37.429860000000005,"longitude":175.12906},{"latitude":-37.42446,"longitude":175.12517000000003},{"latitude":-37.41235,"longitude":175.12573},{"latitude":-37.402820000000006,"longitude":175.11977000000002},{"latitude":-37.393390000000004,"longitude":175.10936},{"latitude":-37.38481,"longitude":175.10383000000002},{"latitude":-37.375490000000006,"longitude":175.09644},{"latitude":-37.368610000000004,"longitude":175.09283000000002},{"latitude":-37.357620000000004,"longitude":175.08503000000002},{"latitude":-37.347570000000005,"longitude":175.07487},{"latitude":-37.339200000000005,"longitude":175.06317},{"latitude":-37.333020000000005,"longitude":175.06234},{"latitude":-37.32652,"longitude":175.06579000000002},{"latitude":-37.3151,"longitude":175.06629},{"latitude":-37.307550000000006,"longitude":175.06668000000002},{"latitude":-37.301500000000004,"longitude":175.06118},{"latitude":-37.292860000000005,"longitude":175.05838000000003},{"latitude":-37.28181,"longitude":175.04892},{"latitude":-37.2648,"longitude":175.04445},{"latitude":-37.260690000000004,"longitude":175.04020000000003},{"latitude":-37.254630000000006,"longitude":175.03733000000003},{"latitude":-37.25224,"longitude":175.03055},{"latitude":-37.245380000000004,"longitude":175.02630000000002},{"latitude":-37.23856,"longitude":175.0206},{"latitude":-37.23284,"longitude":175.0191},{"latitude":-37.225910000000006,"longitude":175.00971},{"latitude":-37.220110000000005,"longitude":175.00127},{"latitude":-37.213440000000006,"longitude":174.99885},{"latitude":-37.20685,"longitude":174.99466},{"latitude":-37.20232,"longitude":174.98963},{"latitude":-37.19664,"longitude":174.98612000000003},{"latitude":-37.18896,"longitude":174.9814},{"latitude":-37.177260000000004,"longitude":174.9813},{"latitude":-37.168510000000005,"longitude":174.98441000000003},{"latitude":-37.13662,"longitude":174.96536},{"latitude":-37.11903,"longitude":174.95401},{"latitude":-37.114090000000004,"longitude":174.94821000000002},{"latitude":-37.102880000000006,"longitude":174.94520000000003},{"latitude":-37.091910000000006,"longitude":174.94191},{"latitude":-37.06373,"longitude":174.92502000000002},{"latitude":-37.04093,"longitude":174.91045000000003},{"latitude":-37.019490000000005,"longitude":174.90919000000002},{"latitude":-37.00555,"longitude":174.89678},{"latitude":-36.989340000000006,"longitude":174.88632},{"latitude":-36.971560000000004,"longitude":174.87771},{"latitude":-36.95436,"longitude":174.85986000000003},{"latitude":-36.93618,"longitude":174.85235},{"latitude":-36.92186,"longitude":174.84601},{"latitude":-36.915220000000005,"longitude":174.82705},{"latitude":-36.910540000000005,"longitude":174.82147},{"latitude":-36.90511,"longitude":174.81365000000002},{"latitude":-36.896930000000005,"longitude":174.80762000000001},{"latitude":-36.88904,"longitude":174.7973},{"latitude":-36.877050000000004,"longitude":174.78169000000003},{"latitude":-36.87319,"longitude":174.77583},{"latitude":-36.86746,"longitude":174.7682},{"latitude":-36.86384,"longitude":174.76561},{"latitude":-36.85906,"longitude":174.76321000000002},{"latitude":-36.856,"longitude":174.76573000000002},{"latitude":-36.85286,"longitude":174.76548000000003}]}`

**Comment by titou71** [comment]
Hi,

Same issue for me. 
Anyone has a solution ?

Thank you,

**Comment by sTorro** [comment]
I am not sure if it will be legal but... I've the data downloaded, I can upload it to gdrive or similar.

**Comment by mrAceT** [comment]
A link would be appreciated

**Comment by sTorro** [comment]
https://drive.google.com/drive/folders/1EdpJe9O2vXsKdop_yRr_ZbnPKHakO57j?usp=sharing

**Comment by WolfgangK** [comment]
@sTorro thank you very much for sharing the files. You saved my day!

**Comment by paulsUsername** [comment]
Thank you sTorro!! 🙌🏻

**Comment by AhmadMaroofKarimi** [comment]
> https://drive.google.com/drive/folders/1EdpJe9O2vXsKdop_yRr_ZbnPKHakO57j?usp=sharing

Hi Can you please tell me, how can I get elevations from .tif file in python

**Comment by Jorl17** [comment]
Hi.

For the better part of the last 2 years, the API has been completely overloaded (sadly, **very little comes in the way of donations,** and so I can't really pay for a more beefed up machine).

**As of two days ago, though, I have done some tweaks to the backend and the API should be handling the workload much better. Give it a try again!**

I will also be **pushing a series of updates to the repository and dockerhub, to modernize the project and make it work again.**

I will close this issue because I believe that this issue is solved, but feel free to reopen it if it is not. If you have any other issues, please open a separate issue for that.
