### ISSUE TITLE
[CRITICAL] WORKER TIMEOUT 

### ISSUE THREAD

**Issue by jeancaffou** [Jorl17/open-elevation#34]
Running from docker or locally, server timeouts requests.

> Bottle v0.12.13 server starting up (using GunicornServer(workers=2))...
> Listening on http://0.0.0.0:8080/
> Hit Ctrl-C to quit.
> 
> [2019-09-07 20:38:18 +0000] [6] [INFO] Starting gunicorn 19.7.1
> [2019-09-07 20:38:18 +0000] [6] [INFO] Listening at: http://0.0.0.0:8080 (6)
> [2019-09-07 20:38:18 +0000] [6] [INFO] Using worker: sync
> [2019-09-07 20:38:18 +0000] [13] [INFO] Booting worker with pid: 13
> [2019-09-07 20:38:18 +0000] [14] [INFO] Booting worker with pid: 14
> [2019-09-07 20:38:55 +0000] [6] [CRITICAL] WORKER TIMEOUT (pid:13)
> [2019-09-07 20:38:56 +0000] [15] [INFO] Booting worker with pid: 15

Trying to POST to http://localhost:8080/api/v1/lookup
`{"locations":[{"latitude":42.686966666667,"longitude":24.7498},{"latitude":42.684416666667,"longitude":24.75005},{"latitude":42.684966666667,"longitude":24.75125},{"latitude":42.684966666667,"longitude":24.752533333333},{"latitude":42.68585,"longitude":24.755416666667},{"latitude":42.68745,"longitude":24.764133333333},{"latitude":42.691733333333,"longitude":24.769433333333},{"latitude":42.690866666667,"longitude":24.771133333333},{"latitude":42.693033333333,"longitude":24.774866666667},{"latitude":42.69195,"longitude":24.784183333333},{"latitude":42.689816666667,"longitude":24.790016666667},{"latitude":42.6898,"longitude":24.7896},{"latitude":42.689583333333,"longitude":24.78885},{"latitude":42.686716666667,"longitude":24.794266666667},{"latitude":42.6829,"longitude":24.7999},{"latitude":42.67855,"longitude":24.8072},{"latitude":42.6777,"longitude":24.815166666667},{"latitude":42.678133333333,"longitude":24.822633333333},{"latitude":42.676766666667,"longitude":24.83055},{"latitude":42.67425,"longitude":24.83845},{"latitude":42.675,"longitude":24.8418},{"latitude":42.671533333333,"longitude":24.846616666667},{"latitude":42.666566666667,"longitude":24.85245},{"latitude":42.66165,"longitude":24.85915},{"latitude":42.657433333333,"longitude":24.864616666667},{"latitude":42.658383333333,"longitude":24.865516666667},{"latitude":42.659033333333,"longitude":24.868033333333},{"latitude":42.658933333333,"longitude":24.8701},{"latitude":42.657133333333,"longitude":24.875266666667},{"latitude":42.658166666667,"longitude":24.875383333333},{"latitude":42.657983333333,"longitude":24.881633333333},{"latitude":42.658416666667,"longitude":24.8879},{"latitude":42.660366666667,"longitude":24.89485},{"latitude":42.662566666667,"longitude":24.901516666667},{"latitude":42.664133333333,"longitude":24.905333333333},{"latitude":42.66655,"longitude":24.9115},{"latitude":42.6683,"longitude":24.912433333333},{"latitude":42.669533333333,"longitude":24.913683333333},{"latitude":42.670516666667,"longitude":24.920966666667},{"latitude":42.672166666667,"longitude":24.926316666667},{"latitude":42.672616666667,"longitude":24.928183333333},{"latitude":42.675116666667,"longitude":24.93165},{"latitude":42.6763,"longitude":24.939866666667},{"latitude":42.67625,"longitude":24.947716666667},{"latitude":42.6805,"longitude":24.9541},{"latitude":42.68205,"longitude":24.955483333333},{"latitude":42.68205,"longitude":24.961416666667},{"latitude":42.681583333333,"longitude":24.97005},{"latitude":42.681166666667,"longitude":24.97935},{"latitude":42.682633333333,"longitude":24.986316666667},{"latitude":42.68275,"longitude":24.995216666667},{"latitude":42.682533333333,"longitude":25.00385},{"latitude":42.6833,"longitude":25.006033333333},{"latitude":42.682066666667,"longitude":25.014},{"latitude":42.680866666667,"longitude":25.019316666667},{"latitude":42.68005,"longitude":25.025533333333},{"latitude":42.67885,"longitude":25.031833333333},{"latitude":42.677916666667,"longitude":25.0377},{"latitude":42.6792,"longitude":25.0453},{"latitude":42.678866666667,"longitude":25.051966666667},{"latitude":42.677583333333,"longitude":25.0585},{"latitude":42.676583333333,"longitude":25.065283333333},{"latitude":42.674683333333,"longitude":25.07025},{"latitude":42.67495,"longitude":25.073316666667},{"latitude":42.676016666667,"longitude":25.074183333333},{"latitude":42.678766666667,"longitude":25.072766666667},{"latitude":42.680883333333,"longitude":25.0717},{"latitude":42.6833,"longitude":25.07025},{"latitude":42.685933333333,"longitude":25.071033333333},{"latitude":42.68485,"longitude":25.076666666667},{"latitude":42.68455,"longitude":25.083916666667},{"latitude":42.685216666667,"longitude":25.091},{"latitude":42.6852,"longitude":25.096666666667},{"latitude":42.6836,"longitude":25.1035},{"latitude":42.68185,"longitude":25.109333333333},{"latitude":42.682733333333,"longitude":25.113766666667},{"latitude":42.684916666667,"longitude":25.113216666667},{"latitude":42.685933333333,"longitude":25.112666666667},{"latitude":42.686783333333,"longitude":25.114083333333},{"latitude":42.687883333333,"longitude":25.120533333333},{"latitude":42.688683333333,"longitude":25.128916666667},{"latitude":42.689716666667,"longitude":25.1376},{"latitude":42.689933333333,"longitude":25.146666666667},{"latitude":42.689383333333,"longitude":25.155733333333},{"latitude":42.68965,"longitude":25.162983333333},{"latitude":42.689116666667,"longitude":25.16925},{"latitude":42.68795,"longitude":25.176733333333},{"latitude":42.688816666667,"longitude":25.185433333333},{"latitude":42.689266666667,"longitude":25.19525},{"latitude":42.688733333333,"longitude":25.2056},{"latitude":42.6898,"longitude":25.216116666667},{"latitude":42.690516666667,"longitude":25.22495},{"latitude":42.691466666667,"longitude":25.23305},{"latitude":42.693416666667,"longitude":25.239833333333},{"latitude":42.69335,"longitude":25.245466666667},{"latitude":42.691533333333,"longitude":25.247766666667},{"latitude":42.691283333333,"longitude":25.247616666667},{"latitude":42.689333333333,"longitude":25.251483333333},{"latitude":42.689066666667,"longitude":25.258333333333},{"latitude":42.689616666667,"longitude":25.267666666667},{"latitude":42.691183333333,"longitude":25.2752},{"latitude":42.691916666667,"longitude":25.281183333333},{"latitude":42.6933,"longitude":25.287633333333},{"latitude":42.692166666667,"longitude":25.289416666667},{"latitude":42.688283333333,"longitude":25.2831},{"latitude":42.683266666667,"longitude":25.2766},{"latitude":42.676766666667,"longitude":25.271433333333},{"latitude":42.669366666667,"longitude":25.269},{"latitude":42.661366666667,"longitude":25.265166666667},{"latitude":42.653566666667,"longitude":25.260633333333},{"latitude":42.646916666667,"longitude":25.2553},{"latitude":42.64085,"longitude":25.25005},{"latitude":42.636333333333,"longitude":25.24445},{"latitude":42.63245,"longitude":25.2424},{"latitude":42.626933333333,"longitude":25.23675},{"latitude":42.620533333333,"longitude":25.232166666667},{"latitude":42.614366666667,"longitude":25.22745},{"latitude":42.608416666667,"longitude":25.22425},{"latitude":42.602733333333,"longitude":25.218833333333},{"latitude":42.5968,"longitude":25.213216666667},{"latitude":42.592383333333,"longitude":25.209133333333},{"latitude":42.5916,"longitude":25.205633333333},{"latitude":42.59075,"longitude":25.203266666667},{"latitude":42.5889,"longitude":25.201333333333},{"latitude":42.588333333333,"longitude":25.199416666667},{"latitude":42.588383333333,"longitude":25.1958},{"latitude":42.58825,"longitude":25.194016666667},{"latitude":42.589683333333,"longitude":25.192},{"latitude":42.5866,"longitude":25.1888},{"latitude":42.583633333333,"longitude":25.1878},{"latitude":42.57935,"longitude":25.178916666667},{"latitude":42.5771,"longitude":25.16915},{"latitude":42.576183333333,"longitude":25.16495},{"latitude":42.57175,"longitude":25.163566666667},{"latitude":42.565,"longitude":25.163033333333},{"latitude":42.558066666667,"longitude":25.161616666667},{"latitude":42.556,"longitude":25.154433333333},{"latitude":42.558916666667,"longitude":25.1456},{"latitude":42.560283333333,"longitude":25.136633333333},{"latitude":42.5639,"longitude":25.12775},{"latitude":42.5684,"longitude":25.120183333333},{"latitude":42.571966666667,"longitude":25.114466666667},{"latitude":42.573516666667,"longitude":25.11335},{"latitude":42.57395,"longitude":25.1114},{"latitude":42.57435,"longitude":25.108433333333},{"latitude":42.575383333333,"longitude":25.1061},{"latitude":42.5755,"longitude":25.1053},{"latitude":42.572416666667,"longitude":25.09785},{"latitude":42.571333333333,"longitude":25.09255},{"latitude":42.570233333333,"longitude":25.090566666667},{"latitude":42.5687,"longitude":25.089166666667},{"latitude":42.56665,"longitude":25.086466666667},{"latitude":42.566216666667,"longitude":25.082566666667},{"latitude":42.56135,"longitude":25.07835},{"latitude":42.556333333333,"longitude":25.0705},{"latitude":42.552166666667,"longitude":25.062716666667},{"latitude":42.549933333333,"longitude":25.05405},{"latitude":42.5492,"longitude":25.04415},{"latitude":42.54835,"longitude":25.034316666667},{"latitude":42.548966666667,"longitude":25.023716666667},{"latitude":42.550766666667,"longitude":25.013083333333},{"latitude":42.551866666667,"longitude":25.0061},{"latitude":42.553433333333,"longitude":24.995},{"latitude":42.552466666667,"longitude":24.988133333333},{"latitude":42.551283333333,"longitude":24.986183333333},{"latitude":42.550416666667,"longitude":24.984583333333},{"latitude":42.548233333333,"longitude":24.984683333333},{"latitude":42.546866666667,"longitude":24.981516666667},{"latitude":42.539416666667,"longitude":24.97685},{"latitude":42.530916666667,"longitude":24.974183333333},{"latitude":42.525083333333,"longitude":24.970366666667},{"latitude":42.521,"longitude":24.965616666667},{"latitude":42.515183333333,"longitude":24.962233333333},{"latitude":42.508383333333,"longitude":24.960216666667},{"latitude":42.501516666667,"longitude":24.954783333333},{"latitude":42.494983333333,"longitude":24.9486},{"latitude":42.488,"longitude":24.941466666667},{"latitude":42.480666666667,"longitude":24.93525},{"latitude":42.4732,"longitude":24.927666666667},{"latitude":42.466733333333,"longitude":24.919833333333},{"latitude":42.4603,"longitude":24.911266666667},{"latitude":42.456816666667,"longitude":24.907716666667},{"latitude":42.452816666667,"longitude":24.905583333333},{"latitude":42.446733333333,"longitude":24.897733333333},{"latitude":42.44165,"longitude":24.890216666667},{"latitude":42.435616666667,"longitude":24.8838},{"latitude":42.4319,"longitude":24.880033333333},{"latitude":42.4311,"longitude":24.8783},{"latitude":42.431983333333,"longitude":24.872933333333},{"latitude":42.434916666667,"longitude":24.866783333333},{"latitude":42.43725,"longitude":24.863683333333},{"latitude":42.4426,"longitude":24.857266666667},{"latitude":42.4469,"longitude":24.854266666667},{"latitude":42.452216666667,"longitude":24.8488},{"latitude":42.458016666667,"longitude":24.843083333333},{"latitude":42.45845,"longitude":24.84075},{"latitude":42.461216666667,"longitude":24.837666666667},{"latitude":42.466666666667,"longitude":24.83},{"latitude":42.471683333333,"longitude":24.825133333333},{"latitude":42.477066666667,"longitude":24.820866666667},{"latitude":42.482283333333,"longitude":24.8186},{"latitude":42.485983333333,"longitude":24.818383333333},{"latitude":42.491366666667,"longitude":24.81535},{"latitude":42.489416666667,"longitude":24.80875},{"latitude":42.48685,"longitude":24.80205},{"latitude":42.48625,"longitude":24.798},{"latitude":42.4844,"longitude":24.794933333333},{"latitude":42.482533333333,"longitude":24.793633333333},{"latitude":42.483983333333,"longitude":24.793666666667},{"latitude":42.484083333333,"longitude":24.79105},{"latitude":42.4841,"longitude":24.790716666667},{"latitude":42.48515,"longitude":24.78945},{"latitude":42.4848,"longitude":24.789783333333},{"latitude":42.486483333333,"longitude":24.788516666667},{"latitude":42.48845,"longitude":24.7893},{"latitude":42.48955,"longitude":24.788616666667},{"latitude":42.4895,"longitude":24.787816666667},{"latitude":42.48855,"longitude":24.785233333333},{"latitude":42.488583333333,"longitude":24.7841},{"latitude":42.487716666667,"longitude":24.78335},{"latitude":42.487316666667,"longitude":24.783283333333},{"latitude":42.489,"longitude":24.780316666667},{"latitude":42.493833333333,"longitude":24.778366666667},{"latitude":42.499633333333,"longitude":24.776116666667},{"latitude":42.504666666667,"longitude":24.775866666667},{"latitude":42.510516666667,"longitude":24.775983333333},{"latitude":42.5172,"longitude":24.77575},{"latitude":42.519516666667,"longitude":24.774366666667},{"latitude":42.52115,"longitude":24.77135},{"latitude":42.524016666667,"longitude":24.769566666667},{"latitude":42.52535,"longitude":24.767166666667},{"latitude":42.529116666667,"longitude":24.7699},{"latitude":42.531516666667,"longitude":24.769516666667},{"latitude":42.532483333333,"longitude":24.769083333333},{"latitude":42.534066666667,"longitude":24.7695},{"latitude":42.534583333333,"longitude":24.770066666667},{"latitude":42.53435,"longitude":24.768883333333},{"latitude":42.534633333333,"longitude":24.766066666667},{"latitude":42.539433333333,"longitude":24.764616666667},{"latitude":42.539833333333,"longitude":24.7638},{"latitude":42.5453,"longitude":24.760583333333},{"latitude":42.5479,"longitude":24.758333333333},{"latitude":42.5501,"longitude":24.754433333333},{"latitude":42.55665,"longitude":24.751233333333},{"latitude":42.562933333333,"longitude":24.747366666667},{"latitude":42.569816666667,"longitude":24.745816666667},{"latitude":42.576133333333,"longitude":24.74495},{"latitude":42.583366666667,"longitude":24.743833333333},{"latitude":42.590766666667,"longitude":24.74305},{"latitude":42.5985,"longitude":24.743},{"latitude":42.605833333333,"longitude":24.742916666667},{"latitude":42.612483333333,"longitude":24.742916666667},{"latitude":42.61905,"longitude":24.743233333333},{"latitude":42.620233333333,"longitude":24.742716666667},{"latitude":42.622416666667,"longitude":24.743},{"latitude":42.6223,"longitude":24.742216666667},{"latitude":42.62435,"longitude":24.740133333333},{"latitude":42.630466666667,"longitude":24.74065},{"latitude":42.637083333333,"longitude":24.74125},{"latitude":42.642933333333,"longitude":24.742033333333},{"latitude":42.645333333333,"longitude":24.739633333333},{"latitude":42.645833333333,"longitude":24.738216666667},{"latitude":42.642366666667,"longitude":24.739783333333},{"latitude":42.640116666667,"longitude":24.741516666667},{"latitude":42.6441,"longitude":24.748083333333},{"latitude":42.647433333333,"longitude":24.751583333333},{"latitude":42.64805,"longitude":24.750866666667},{"latitude":42.648833333333,"longitude":24.75275},{"latitude":42.648266666667,"longitude":24.7535},{"latitude":42.65055,"longitude":24.7533},{"latitude":42.6523,"longitude":24.752633333333},{"latitude":42.654966666667,"longitude":24.751233333333},{"latitude":42.656566666667,"longitude":24.751816666667},{"latitude":42.65895,"longitude":24.74995},{"latitude":42.661966666667,"longitude":24.748883333333},{"latitude":42.663833333333,"longitude":24.747283333333},{"latitude":42.666016666667,"longitude":24.746016666667},{"latitude":42.668533333333,"longitude":24.743266666667},{"latitude":42.672816666667,"longitude":24.739833333333},{"latitude":42.679233333333,"longitude":24.734433333333},{"latitude":42.68475,"longitude":24.729516666667},{"latitude":42.69055,"longitude":24.723983333333},{"latitude":42.696916666667,"longitude":24.716833333333},{"latitude":42.7019,"longitude":24.710716666667},{"latitude":42.70425,"longitude":24.709116666667},{"latitude":42.70975,"longitude":24.70375},{"latitude":42.71195,"longitude":24.700716666667},{"latitude":42.716466666667,"longitude":24.6925},{"latitude":42.719533333333,"longitude":24.684466666667},{"latitude":42.723466666667,"longitude":24.676},{"latitude":42.72725,"longitude":24.671916666667},{"latitude":42.72925,"longitude":24.6682},{"latitude":42.733716666667,"longitude":24.658883333333},{"latitude":42.736033333333,"longitude":24.648783333333},{"latitude":42.7372,"longitude":24.642016666667},{"latitude":42.7376,"longitude":24.634066666667},{"latitude":42.739433333333,"longitude":24.624333333333},{"latitude":42.740716666667,"longitude":24.61745},{"latitude":42.741983333333,"longitude":24.612833333333},{"latitude":42.740616666667,"longitude":24.61315},{"latitude":42.74045,"longitude":24.608666666667},{"latitude":42.737766666667,"longitude":24.60005},{"latitude":42.735783333333,"longitude":24.599016666667},{"latitude":42.735766666667,"longitude":24.6056},{"latitude":42.735683333333,"longitude":24.611416666667},{"latitude":42.737016666667,"longitude":24.615816666667},{"latitude":42.737,"longitude":24.6222},{"latitude":42.738716666667,"longitude":24.622416666667},{"latitude":42.741783333333,"longitude":24.622466666667},{"latitude":42.744083333333,"longitude":24.621516666667},{"latitude":42.742416666667,"longitude":24.627766666667},{"latitude":42.740333333333,"longitude":24.6358},{"latitude":42.738816666667,"longitude":24.64375},{"latitude":42.736983333333,"longitude":24.650283333333},{"latitude":42.734,"longitude":24.65685},{"latitude":42.730783333333,"longitude":24.665183333333},{"latitude":42.727816666667,"longitude":24.670783333333},{"latitude":42.725083333333,"longitude":24.674233333333},{"latitude":42.722733333333,"longitude":24.679366666667},{"latitude":42.7207,"longitude":24.68315},{"latitude":42.717716666667,"longitude":24.68625},{"latitude":42.715616666667,"longitude":24.69175},{"latitude":42.7158,"longitude":24.695616666667},{"latitude":42.7169,"longitude":24.70245},{"latitude":42.715983333333,"longitude":24.708066666667},{"latitude":42.713583333333,"longitude":24.7145},{"latitude":42.711383333333,"longitude":24.720716666667},{"latitude":42.7096,"longitude":24.725633333333},{"latitude":42.706783333333,"longitude":24.7302},{"latitude":42.704716666667,"longitude":24.734783333333},{"latitude":42.702733333333,"longitude":24.738716666667},{"latitude":42.702866666667,"longitude":24.740916666667},{"latitude":42.702016666667,"longitude":24.743383333333},{"latitude":42.703,"longitude":24.745516666667},{"latitude":42.70085,"longitude":24.751316666667},{"latitude":42.698183333333,"longitude":24.757833333333},{"latitude":42.695966666667,"longitude":24.763966666667},{"latitude":42.693133333333,"longitude":24.769383333333},{"latitude":42.690166666667,"longitude":24.775866666667},{"latitude":42.687333333333,"longitude":24.78215},{"latitude":42.684333333333,"longitude":24.787116666667},{"latitude":42.681116666667,"longitude":24.7913},{"latitude":42.682633333333,"longitude":24.7922},{"latitude":42.679433333333,"longitude":24.79685},{"latitude":42.675766666667,"longitude":24.801516666667},{"latitude":42.6734,"longitude":24.806366666667},{"latitude":42.670933333333,"longitude":24.810566666667},{"latitude":42.66815,"longitude":24.805683333333},{"latitude":42.666183333333,"longitude":24.798366666667},{"latitude":42.665666666667,"longitude":24.789583333333},{"latitude":42.664766666667,"longitude":24.7811},{"latitude":42.663733333333,"longitude":24.7728},{"latitude":42.662683333333,"longitude":24.7657},{"latitude":42.65935,"longitude":24.760233333333},{"latitude":42.655866666667,"longitude":24.754433333333},{"latitude":42.652116666667,"longitude":24.749216666667},{"latitude":42.655033333333,"longitude":24.7441},{"latitude":42.656133333333,"longitude":24.747266666667},{"latitude":42.658316666667,"longitude":24.7469},{"latitude":42.660133333333,"longitude":24.745383333333},{"latitude":42.66165,"longitude":24.747816666667},{"latitude":42.664816666667,"longitude":24.746033333333},{"latitude":42.662033333333,"longitude":24.747016666667},{"latitude":42.664133333333,"longitude":24.7442},{"latitude":42.662066666667,"longitude":24.74555},{"latitude":42.665316666667,"longitude":24.747466666667},{"latitude":42.663933333333,"longitude":24.747833333333}]}`

**Comment by jeancaffou** [comment]
No, this is a local instalation (in Docker), it should be working out of the box. It is not dependent on the public API resources.

**Comment by Jorl17** [comment]
Hi!

It seems workers are timing out while answering requests. How big are your tiles? Are you positive you have enough resources available (e.g. is the machine thrashing?)

Regards

**Comment by jeancaffou** [comment]
Using STRM 250m, and 10x10 tiles created as per documentation.
Machine resources are 16 GB ram (without swap), Intel(R) Xeon(R) CPU X5650  @ 2.67GHz, and enough disk space.

**Comment by Cl00e9ment** [comment]
Got the same issue.

Did you leave the original `SRTM_NE_250m.tif` file in the `data` directory?
If so, delete it an leave only the files generated by the `create-tiles.sh` script. It solved the issue for me.

**Comment by jeancaffou** [comment]
:man_facepalming:
