### ISSUE TITLE
Requests limit/quota?

### ISSUE THREAD

**Issue by aershov24** [Jorl17/open-elevation#4]
Hi guys, really appreciate your work. Is there any requests limit/quota?

**Comment by Jorl17** [comment]
Hi, I'd like to point you to [my reply regarding this issue, here](https://github.com/Jorl17/open-elevation/issues/3#issuecomment-359216000) :)

**Comment by Jorl17** [comment]
I'll also close this issue. You can use the one I linked before to discuss requests limits and quotas :)
