### ISSUE TITLE
Unable to download the whole world dataset 404

### ISSUE THREAD

**Issue by AmitSuri** [Jorl17/open-elevation#42]
`docker run -t -i -v $(pwd)/data:/code/data openelevation/open-elevation /code/create-dataset.sh`
```

--2021-03-28 17:04:33--  http://gisweb.ciat.cgiar.org/TRMM/SRTM_Resampled_250m/SRTM_NE_250m_TIF.rar
Resolving gisweb.ciat.cgiar.org (gisweb.ciat.cgiar.org)... 45.5.184.33
Connecting to gisweb.ciat.cgiar.org (gisweb.ciat.cgiar.org)|45.5.184.33|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-03-28 17:04:34 ERROR 404: Not Found.
```

**Comment by gehr-luk** [comment]
I am facing the same issue. 
My guess was that the URL is not up to date anymore.

But changing it to the possibly correct one in `download-srtm-data.sh` like this:
```bash
#!/usr/bin/env bash

set -eu

wget https://srtm.csi.cgiar.org/wp-content/uploads/files/250m/SRTM_NE_250m_TIF.rar && \
wget https://srtm.csi.cgiar.org/wp-content/uploads/files/250m/SRTM_SE_250m_TIF.rar && \
wget https://srtm.csi.cgiar.org/wp-content/uploads/files/250m/SRTM_W_250m_TIF.rar && \
unar -f SRTM_NE_250m_TIF.rar && \
unar -f SRTM_SE_250m_TIF.rar && \
unar -f SRTM_W_250m_TIF.rar
```

did not help. 
Error is still:
```
❯ docker run -t -i -v ${pwd}/data:/code/data openelevation/open-elevation /code/create-dataset.sh
--2021-03-28 19:32:36--  http://gisweb.ciat.cgiar.org/TRMM/SRTM_Resampled_250m/SRTM_NE_250m_TIF.rar
Resolving gisweb.ciat.cgiar.org (gisweb.ciat.cgiar.org)... 45.5.184.33
Connecting to gisweb.ciat.cgiar.org (gisweb.ciat.cgiar.org)|45.5.184.33|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-03-28 19:32:36 ERROR 404: Not Found.
```
Maybe I am missing something with updating the docker container or something. Because the URL is not beeing updated in the logs.
Any help would be appreciated.

**Comment by AmitSuri** [comment]
Found this in one of the comments. it works
source: https://github.com/Jorl17/open-elevation/issues/38 

charlycou commented 17 days ago
SRTM data are now located at https://srtm.csi.cgiar.org/wp-content/uploads/files/250m/. You can either change the download-srtm-data.sh script and rebuild your own image or download the data yourself and mount them on your container as described in the documentation.

**Comment by AmitSuri** [comment]
is this project abandoned by any chance?

**Comment by JLundqvist** [comment]
Easiest way is to map a local, updated, copy of download-srtm-data.sh

`docker run -t -i -v $(pwd)/data:/code/data -v $(pwd)/download-srtm-data.sh:/code/download-srtm-data.sh openelevation/open-elevation /code/create-dataset.sh`

download-srtm-data.sh should look like this:
`#!/usr/bin/env bash

set -eu

wget https://srtm.csi.cgiar.org/wp-content/uploads/files/250m/SRTM_NE_250m_TIF.rar && \
wget https://srtm.csi.cgiar.org/wp-content/uploads/files/250m/SRTM_SE_250m_TIF.rar && \
wget https://srtm.csi.cgiar.org/wp-content/uploads/files/250m/SRTM_W_250m_TIF.rar && \
unar -f SRTM_NE_250m_TIF.rar && \
unar -f SRTM_SE_250m_TIF.rar && \
unar -f SRTM_W_250m_TIF.rar
`

**Comment by JLundqvist** [comment]
Oh, and you also have to either update `create-dataset.sh` or `download-srtm-data.sh`, since the TIF-files are unpacked into folders in the version from srtm.csi.cgiar.org
Or you could just simply move them manually, as I did when I found out why it still didn't work.

**Comment by Jorl17** [comment]
Hi.

For the better part of the last 2 years, the API has been completely overloaded (sadly, **very little comes in the way of donations,** and so I can't really pay for a more beefed up machine).

**As of two days ago, though, I have done some tweaks to the backend and the API should be handling the workload much better. Give it a try again!**

I will also be **pushing a series of updates to the repository and dockerhub, to modernize the project and make it work again.** This includes fixing the Dockerfile and updating the source dataset.

When that happens, I will close this issue.
