### ISSUE TITLE
Add support for request elevations along a path

### ISSUE THREAD

**Issue by webmap2015** [Jorl17/open-elevation#44]
Hi,

Like
https://www.jawg.io/docs/apidocs/elevation/#request-elevations-along-a-path

Thanks.

**Comment by Jorl17** [comment]
Hi.

We support this already using the `lat,lng|lat,lng|lat,lng` syntax. Were you looking for additional support for a polyline?

**Comment by wzharith** [comment]
Hi,

I am also looking forward for this type of support. currently lat,lng|lat,lng|lat,lng only will give the output for 3 points. It would be great if it can provide for a polyline. From PointA to Point B.

**Comment by webmap2015** [comment]
I made it.
