### ISSUE TITLE
ping api.open-elevation.com: 100% packet loss

### ISSUE THREAD

**Issue by vsevjednom-cz** [Jorl17/open-elevation#47]
I'm trying to fix altitude values in my GPX file. But I can't connect to api.open-elevation.com and IP address 46.101.224.40. Connection failed with wget. Ping failed too: `100% packet loss`. Is any problem with IP address of my VPS? Everything works without problem from home.

**Comment by Jorl17** [comment]
Hi!

The gateway machine is currently hosted on DigitalOcean and nothing particularly fancy should be going on with the IP. It sounds like there's some problem with the connection you're using, as it seems to be blocking requests for this IP (and probably others).

Cheers,
João Ricardo Lourenço

**Comment by vsevjednom-cz** [comment]
Hi, it works right now. I don't know where was a problem 🤪.
