### ISSUE TITLE
error 404 not found

### ISSUE THREAD

**Issue by aliceholvoet** [Jorl17/open-elevation#48]
Hi, i'm trying to use this API for the first time. I think I manage to solve ssl problem by using urllib
however the example given in https://github.com/Jorl17/open-elevation/blob/master/docs/api.md returns error 404 :
 
"Sorry, the requested URL 'http://api.open-elevation.com/api/v1/lookup/?locations\\=10,10\\|20,20\\|41.161758,-8.583933' caused an error:

Not found: '/api/v1/lookup/'"

Is the API currently not working or am I missing something in how to use it ?
Thanks

**Comment by Jorl17** [comment]
Hi.

The documentation you mention has a shell command, and therefore the command has slashes escaping some of its elements. Notice how parts of the URL are `\|`, for example.

The actual request URL is https://api.open-elevation.com/api/v1/lookup?locations=10,10|20,20|41.161758,-8.583933 , which seems to be working.

**Comment by Jorl17** [comment]
I've addressed this potential documentation confusion with commit https://github.com/Jorl17/open-elevation/commit/677f9de1b6c1a10b48028f36e072bf8b6ba19b9e. I'll close the issue. Feel free to reopen it if this didn't solve your problem.

**Comment by aliceholvoet** [comment]
Perfect, thanks !
