### ISSUE TITLE
TLS certificate for `open-elevation.com` has expired

### ISSUE THREAD

**Issue by netr0m** [Jorl17/open-elevation#66]
Expires on: Sunday, October 23, 2022 at 11:20:06 AM
![2022-10-24_10-40](https://user-images.githubusercontent.com/16702264/197484950-d610ae05-bf47-420b-aaa7-c6322437e54b.png)

**Comment by Jorl17** [comment]
Thank you for your report. Should be fixed now. My apologies.

**Comment by mimre25** [comment]
Happened again today.
