### ISSUE TITLE
POST request error

### ISSUE THREAD

**Issue by chrislukic** [Jorl17/open-elevation#9]
I'm receiving a 500 error when testing the new POST request functionality. 

You can replicate the issue with the following curl:

curl -X POST -k -i 'https://api.open-elevation.com/api/v1/lookup' --data '{"locations":[{"latitude":48.877213,"longitude":2.383938},{"latitude":48.877240,"longitude":2.383898}]}'

I was hoping this was a mistake with my json formatting, but wasn't able to identify an issue.

**Comment by Jorl17** [comment]
Hi.!

You are missing the `application/json` headers. The following works:
```
curl -H 'Accept: application/json' -H 'Content-Type: application/json' -X POST -k -i 'https://api.open-elevation.com/api/v1/lookup' --data '{"locations":[{"latitude":48.877213,"longitude":2.383938},{"latitude":48.877240,"longitude":2.383898}]}'```

Nevertheless, the server should not 500, and that has been fixed. Thanks for the report!

**Comment by chrislukic** [comment]
That was it. Server returns the correct error as well now.  Works a charm. Thanks!
